server:
  name: "project-user"
  addr: "127.0.0.1:8080"
zap:
  debugFileName: "E:\\go-code\\ms_project_hub\\logs\\debug\\project-debug.log"
  infoFileName: "E:\\go-code\\ms_project_hub\\logs\\info\\project-info.log"
  warnFileName: "E:\\go-code\\ms_project_hub\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
grpc:
  name: "user"
  addr: "127.0.0.1:8881"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject