server:
  name: "project-user"
  addr: "127.0.0.1:80"
zap:
  debugFileName: "E:\\go-code\\ms_project_hub\\logs\\debug\\project-debug.log"
  infoFileName: "E:\\go-code\\ms_project_hub\\logs\\info\\project-info.log"
  warnFileName: "E:\\go-code\\ms_project_hub\\logs\\error\\project-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0